[supervisord]
nodaemon=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan serve --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
priority=5
numprocs=1
user=root
stdout_logfile=/var/log/supervisor/supervisor.log
stderr_logfile=/var/log/supervisor/supervisor.log
